// Code generated by ent, DO NOT EDIT.

package externalinformation

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/halcyon-org/kizuna/ent/predicate"
	"github.com/halcyon-org/kizuna/ent/schema/pulid"
)

// ID filters vertices based on their ID field.
func ID(id pulid.ID) predicate.ExternalInformation {
	return predicate.ExternalInformation(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id pulid.ID) predicate.ExternalInformation {
	return predicate.ExternalInformation(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id pulid.ID) predicate.ExternalInformation {
	return predicate.ExternalInformation(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...pulid.ID) predicate.ExternalInformation {
	return predicate.ExternalInformation(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...pulid.ID) predicate.ExternalInformation {
	return predicate.ExternalInformation(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id pulid.ID) predicate.ExternalInformation {
	return predicate.ExternalInformation(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id pulid.ID) predicate.ExternalInformation {
	return predicate.ExternalInformation(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id pulid.ID) predicate.ExternalInformation {
	return predicate.ExternalInformation(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id pulid.ID) predicate.ExternalInformation {
	return predicate.ExternalInformation(sql.FieldLTE(FieldID, id))
}

// Name applies equality check predicate on the "name" field. It's identical to NameEQ.
func Name(v string) predicate.ExternalInformation {
	return predicate.ExternalInformation(sql.FieldEQ(FieldName, v))
}

// Description applies equality check predicate on the "description" field. It's identical to DescriptionEQ.
func Description(v string) predicate.ExternalInformation {
	return predicate.ExternalInformation(sql.FieldEQ(FieldDescription, v))
}

// License applies equality check predicate on the "license" field. It's identical to LicenseEQ.
func License(v string) predicate.ExternalInformation {
	return predicate.ExternalInformation(sql.FieldEQ(FieldLicense, v))
}

// LicenseDescription applies equality check predicate on the "license_description" field. It's identical to LicenseDescriptionEQ.
func LicenseDescription(v string) predicate.ExternalInformation {
	return predicate.ExternalInformation(sql.FieldEQ(FieldLicenseDescription, v))
}

// APIKey applies equality check predicate on the "api_key" field. It's identical to APIKeyEQ.
func APIKey(v string) predicate.ExternalInformation {
	return predicate.ExternalInformation(sql.FieldEQ(FieldAPIKey, v))
}

// FirstEntryAt applies equality check predicate on the "first_entry_at" field. It's identical to FirstEntryAtEQ.
func FirstEntryAt(v time.Time) predicate.ExternalInformation {
	return predicate.ExternalInformation(sql.FieldEQ(FieldFirstEntryAt, v))
}

// LastUpdatedAt applies equality check predicate on the "last_updated_at" field. It's identical to LastUpdatedAtEQ.
func LastUpdatedAt(v time.Time) predicate.ExternalInformation {
	return predicate.ExternalInformation(sql.FieldEQ(FieldLastUpdatedAt, v))
}

// NameEQ applies the EQ predicate on the "name" field.
func NameEQ(v string) predicate.ExternalInformation {
	return predicate.ExternalInformation(sql.FieldEQ(FieldName, v))
}

// NameNEQ applies the NEQ predicate on the "name" field.
func NameNEQ(v string) predicate.ExternalInformation {
	return predicate.ExternalInformation(sql.FieldNEQ(FieldName, v))
}

// NameIn applies the In predicate on the "name" field.
func NameIn(vs ...string) predicate.ExternalInformation {
	return predicate.ExternalInformation(sql.FieldIn(FieldName, vs...))
}

// NameNotIn applies the NotIn predicate on the "name" field.
func NameNotIn(vs ...string) predicate.ExternalInformation {
	return predicate.ExternalInformation(sql.FieldNotIn(FieldName, vs...))
}

// NameGT applies the GT predicate on the "name" field.
func NameGT(v string) predicate.ExternalInformation {
	return predicate.ExternalInformation(sql.FieldGT(FieldName, v))
}

// NameGTE applies the GTE predicate on the "name" field.
func NameGTE(v string) predicate.ExternalInformation {
	return predicate.ExternalInformation(sql.FieldGTE(FieldName, v))
}

// NameLT applies the LT predicate on the "name" field.
func NameLT(v string) predicate.ExternalInformation {
	return predicate.ExternalInformation(sql.FieldLT(FieldName, v))
}

// NameLTE applies the LTE predicate on the "name" field.
func NameLTE(v string) predicate.ExternalInformation {
	return predicate.ExternalInformation(sql.FieldLTE(FieldName, v))
}

// NameContains applies the Contains predicate on the "name" field.
func NameContains(v string) predicate.ExternalInformation {
	return predicate.ExternalInformation(sql.FieldContains(FieldName, v))
}

// NameHasPrefix applies the HasPrefix predicate on the "name" field.
func NameHasPrefix(v string) predicate.ExternalInformation {
	return predicate.ExternalInformation(sql.FieldHasPrefix(FieldName, v))
}

// NameHasSuffix applies the HasSuffix predicate on the "name" field.
func NameHasSuffix(v string) predicate.ExternalInformation {
	return predicate.ExternalInformation(sql.FieldHasSuffix(FieldName, v))
}

// NameEqualFold applies the EqualFold predicate on the "name" field.
func NameEqualFold(v string) predicate.ExternalInformation {
	return predicate.ExternalInformation(sql.FieldEqualFold(FieldName, v))
}

// NameContainsFold applies the ContainsFold predicate on the "name" field.
func NameContainsFold(v string) predicate.ExternalInformation {
	return predicate.ExternalInformation(sql.FieldContainsFold(FieldName, v))
}

// DescriptionEQ applies the EQ predicate on the "description" field.
func DescriptionEQ(v string) predicate.ExternalInformation {
	return predicate.ExternalInformation(sql.FieldEQ(FieldDescription, v))
}

// DescriptionNEQ applies the NEQ predicate on the "description" field.
func DescriptionNEQ(v string) predicate.ExternalInformation {
	return predicate.ExternalInformation(sql.FieldNEQ(FieldDescription, v))
}

// DescriptionIn applies the In predicate on the "description" field.
func DescriptionIn(vs ...string) predicate.ExternalInformation {
	return predicate.ExternalInformation(sql.FieldIn(FieldDescription, vs...))
}

// DescriptionNotIn applies the NotIn predicate on the "description" field.
func DescriptionNotIn(vs ...string) predicate.ExternalInformation {
	return predicate.ExternalInformation(sql.FieldNotIn(FieldDescription, vs...))
}

// DescriptionGT applies the GT predicate on the "description" field.
func DescriptionGT(v string) predicate.ExternalInformation {
	return predicate.ExternalInformation(sql.FieldGT(FieldDescription, v))
}

// DescriptionGTE applies the GTE predicate on the "description" field.
func DescriptionGTE(v string) predicate.ExternalInformation {
	return predicate.ExternalInformation(sql.FieldGTE(FieldDescription, v))
}

// DescriptionLT applies the LT predicate on the "description" field.
func DescriptionLT(v string) predicate.ExternalInformation {
	return predicate.ExternalInformation(sql.FieldLT(FieldDescription, v))
}

// DescriptionLTE applies the LTE predicate on the "description" field.
func DescriptionLTE(v string) predicate.ExternalInformation {
	return predicate.ExternalInformation(sql.FieldLTE(FieldDescription, v))
}

// DescriptionContains applies the Contains predicate on the "description" field.
func DescriptionContains(v string) predicate.ExternalInformation {
	return predicate.ExternalInformation(sql.FieldContains(FieldDescription, v))
}

// DescriptionHasPrefix applies the HasPrefix predicate on the "description" field.
func DescriptionHasPrefix(v string) predicate.ExternalInformation {
	return predicate.ExternalInformation(sql.FieldHasPrefix(FieldDescription, v))
}

// DescriptionHasSuffix applies the HasSuffix predicate on the "description" field.
func DescriptionHasSuffix(v string) predicate.ExternalInformation {
	return predicate.ExternalInformation(sql.FieldHasSuffix(FieldDescription, v))
}

// DescriptionEqualFold applies the EqualFold predicate on the "description" field.
func DescriptionEqualFold(v string) predicate.ExternalInformation {
	return predicate.ExternalInformation(sql.FieldEqualFold(FieldDescription, v))
}

// DescriptionContainsFold applies the ContainsFold predicate on the "description" field.
func DescriptionContainsFold(v string) predicate.ExternalInformation {
	return predicate.ExternalInformation(sql.FieldContainsFold(FieldDescription, v))
}

// LicenseEQ applies the EQ predicate on the "license" field.
func LicenseEQ(v string) predicate.ExternalInformation {
	return predicate.ExternalInformation(sql.FieldEQ(FieldLicense, v))
}

// LicenseNEQ applies the NEQ predicate on the "license" field.
func LicenseNEQ(v string) predicate.ExternalInformation {
	return predicate.ExternalInformation(sql.FieldNEQ(FieldLicense, v))
}

// LicenseIn applies the In predicate on the "license" field.
func LicenseIn(vs ...string) predicate.ExternalInformation {
	return predicate.ExternalInformation(sql.FieldIn(FieldLicense, vs...))
}

// LicenseNotIn applies the NotIn predicate on the "license" field.
func LicenseNotIn(vs ...string) predicate.ExternalInformation {
	return predicate.ExternalInformation(sql.FieldNotIn(FieldLicense, vs...))
}

// LicenseGT applies the GT predicate on the "license" field.
func LicenseGT(v string) predicate.ExternalInformation {
	return predicate.ExternalInformation(sql.FieldGT(FieldLicense, v))
}

// LicenseGTE applies the GTE predicate on the "license" field.
func LicenseGTE(v string) predicate.ExternalInformation {
	return predicate.ExternalInformation(sql.FieldGTE(FieldLicense, v))
}

// LicenseLT applies the LT predicate on the "license" field.
func LicenseLT(v string) predicate.ExternalInformation {
	return predicate.ExternalInformation(sql.FieldLT(FieldLicense, v))
}

// LicenseLTE applies the LTE predicate on the "license" field.
func LicenseLTE(v string) predicate.ExternalInformation {
	return predicate.ExternalInformation(sql.FieldLTE(FieldLicense, v))
}

// LicenseContains applies the Contains predicate on the "license" field.
func LicenseContains(v string) predicate.ExternalInformation {
	return predicate.ExternalInformation(sql.FieldContains(FieldLicense, v))
}

// LicenseHasPrefix applies the HasPrefix predicate on the "license" field.
func LicenseHasPrefix(v string) predicate.ExternalInformation {
	return predicate.ExternalInformation(sql.FieldHasPrefix(FieldLicense, v))
}

// LicenseHasSuffix applies the HasSuffix predicate on the "license" field.
func LicenseHasSuffix(v string) predicate.ExternalInformation {
	return predicate.ExternalInformation(sql.FieldHasSuffix(FieldLicense, v))
}

// LicenseEqualFold applies the EqualFold predicate on the "license" field.
func LicenseEqualFold(v string) predicate.ExternalInformation {
	return predicate.ExternalInformation(sql.FieldEqualFold(FieldLicense, v))
}

// LicenseContainsFold applies the ContainsFold predicate on the "license" field.
func LicenseContainsFold(v string) predicate.ExternalInformation {
	return predicate.ExternalInformation(sql.FieldContainsFold(FieldLicense, v))
}

// LicenseDescriptionEQ applies the EQ predicate on the "license_description" field.
func LicenseDescriptionEQ(v string) predicate.ExternalInformation {
	return predicate.ExternalInformation(sql.FieldEQ(FieldLicenseDescription, v))
}

// LicenseDescriptionNEQ applies the NEQ predicate on the "license_description" field.
func LicenseDescriptionNEQ(v string) predicate.ExternalInformation {
	return predicate.ExternalInformation(sql.FieldNEQ(FieldLicenseDescription, v))
}

// LicenseDescriptionIn applies the In predicate on the "license_description" field.
func LicenseDescriptionIn(vs ...string) predicate.ExternalInformation {
	return predicate.ExternalInformation(sql.FieldIn(FieldLicenseDescription, vs...))
}

// LicenseDescriptionNotIn applies the NotIn predicate on the "license_description" field.
func LicenseDescriptionNotIn(vs ...string) predicate.ExternalInformation {
	return predicate.ExternalInformation(sql.FieldNotIn(FieldLicenseDescription, vs...))
}

// LicenseDescriptionGT applies the GT predicate on the "license_description" field.
func LicenseDescriptionGT(v string) predicate.ExternalInformation {
	return predicate.ExternalInformation(sql.FieldGT(FieldLicenseDescription, v))
}

// LicenseDescriptionGTE applies the GTE predicate on the "license_description" field.
func LicenseDescriptionGTE(v string) predicate.ExternalInformation {
	return predicate.ExternalInformation(sql.FieldGTE(FieldLicenseDescription, v))
}

// LicenseDescriptionLT applies the LT predicate on the "license_description" field.
func LicenseDescriptionLT(v string) predicate.ExternalInformation {
	return predicate.ExternalInformation(sql.FieldLT(FieldLicenseDescription, v))
}

// LicenseDescriptionLTE applies the LTE predicate on the "license_description" field.
func LicenseDescriptionLTE(v string) predicate.ExternalInformation {
	return predicate.ExternalInformation(sql.FieldLTE(FieldLicenseDescription, v))
}

// LicenseDescriptionContains applies the Contains predicate on the "license_description" field.
func LicenseDescriptionContains(v string) predicate.ExternalInformation {
	return predicate.ExternalInformation(sql.FieldContains(FieldLicenseDescription, v))
}

// LicenseDescriptionHasPrefix applies the HasPrefix predicate on the "license_description" field.
func LicenseDescriptionHasPrefix(v string) predicate.ExternalInformation {
	return predicate.ExternalInformation(sql.FieldHasPrefix(FieldLicenseDescription, v))
}

// LicenseDescriptionHasSuffix applies the HasSuffix predicate on the "license_description" field.
func LicenseDescriptionHasSuffix(v string) predicate.ExternalInformation {
	return predicate.ExternalInformation(sql.FieldHasSuffix(FieldLicenseDescription, v))
}

// LicenseDescriptionEqualFold applies the EqualFold predicate on the "license_description" field.
func LicenseDescriptionEqualFold(v string) predicate.ExternalInformation {
	return predicate.ExternalInformation(sql.FieldEqualFold(FieldLicenseDescription, v))
}

// LicenseDescriptionContainsFold applies the ContainsFold predicate on the "license_description" field.
func LicenseDescriptionContainsFold(v string) predicate.ExternalInformation {
	return predicate.ExternalInformation(sql.FieldContainsFold(FieldLicenseDescription, v))
}

// APIKeyEQ applies the EQ predicate on the "api_key" field.
func APIKeyEQ(v string) predicate.ExternalInformation {
	return predicate.ExternalInformation(sql.FieldEQ(FieldAPIKey, v))
}

// APIKeyNEQ applies the NEQ predicate on the "api_key" field.
func APIKeyNEQ(v string) predicate.ExternalInformation {
	return predicate.ExternalInformation(sql.FieldNEQ(FieldAPIKey, v))
}

// APIKeyIn applies the In predicate on the "api_key" field.
func APIKeyIn(vs ...string) predicate.ExternalInformation {
	return predicate.ExternalInformation(sql.FieldIn(FieldAPIKey, vs...))
}

// APIKeyNotIn applies the NotIn predicate on the "api_key" field.
func APIKeyNotIn(vs ...string) predicate.ExternalInformation {
	return predicate.ExternalInformation(sql.FieldNotIn(FieldAPIKey, vs...))
}

// APIKeyGT applies the GT predicate on the "api_key" field.
func APIKeyGT(v string) predicate.ExternalInformation {
	return predicate.ExternalInformation(sql.FieldGT(FieldAPIKey, v))
}

// APIKeyGTE applies the GTE predicate on the "api_key" field.
func APIKeyGTE(v string) predicate.ExternalInformation {
	return predicate.ExternalInformation(sql.FieldGTE(FieldAPIKey, v))
}

// APIKeyLT applies the LT predicate on the "api_key" field.
func APIKeyLT(v string) predicate.ExternalInformation {
	return predicate.ExternalInformation(sql.FieldLT(FieldAPIKey, v))
}

// APIKeyLTE applies the LTE predicate on the "api_key" field.
func APIKeyLTE(v string) predicate.ExternalInformation {
	return predicate.ExternalInformation(sql.FieldLTE(FieldAPIKey, v))
}

// APIKeyContains applies the Contains predicate on the "api_key" field.
func APIKeyContains(v string) predicate.ExternalInformation {
	return predicate.ExternalInformation(sql.FieldContains(FieldAPIKey, v))
}

// APIKeyHasPrefix applies the HasPrefix predicate on the "api_key" field.
func APIKeyHasPrefix(v string) predicate.ExternalInformation {
	return predicate.ExternalInformation(sql.FieldHasPrefix(FieldAPIKey, v))
}

// APIKeyHasSuffix applies the HasSuffix predicate on the "api_key" field.
func APIKeyHasSuffix(v string) predicate.ExternalInformation {
	return predicate.ExternalInformation(sql.FieldHasSuffix(FieldAPIKey, v))
}

// APIKeyEqualFold applies the EqualFold predicate on the "api_key" field.
func APIKeyEqualFold(v string) predicate.ExternalInformation {
	return predicate.ExternalInformation(sql.FieldEqualFold(FieldAPIKey, v))
}

// APIKeyContainsFold applies the ContainsFold predicate on the "api_key" field.
func APIKeyContainsFold(v string) predicate.ExternalInformation {
	return predicate.ExternalInformation(sql.FieldContainsFold(FieldAPIKey, v))
}

// FirstEntryAtEQ applies the EQ predicate on the "first_entry_at" field.
func FirstEntryAtEQ(v time.Time) predicate.ExternalInformation {
	return predicate.ExternalInformation(sql.FieldEQ(FieldFirstEntryAt, v))
}

// FirstEntryAtNEQ applies the NEQ predicate on the "first_entry_at" field.
func FirstEntryAtNEQ(v time.Time) predicate.ExternalInformation {
	return predicate.ExternalInformation(sql.FieldNEQ(FieldFirstEntryAt, v))
}

// FirstEntryAtIn applies the In predicate on the "first_entry_at" field.
func FirstEntryAtIn(vs ...time.Time) predicate.ExternalInformation {
	return predicate.ExternalInformation(sql.FieldIn(FieldFirstEntryAt, vs...))
}

// FirstEntryAtNotIn applies the NotIn predicate on the "first_entry_at" field.
func FirstEntryAtNotIn(vs ...time.Time) predicate.ExternalInformation {
	return predicate.ExternalInformation(sql.FieldNotIn(FieldFirstEntryAt, vs...))
}

// FirstEntryAtGT applies the GT predicate on the "first_entry_at" field.
func FirstEntryAtGT(v time.Time) predicate.ExternalInformation {
	return predicate.ExternalInformation(sql.FieldGT(FieldFirstEntryAt, v))
}

// FirstEntryAtGTE applies the GTE predicate on the "first_entry_at" field.
func FirstEntryAtGTE(v time.Time) predicate.ExternalInformation {
	return predicate.ExternalInformation(sql.FieldGTE(FieldFirstEntryAt, v))
}

// FirstEntryAtLT applies the LT predicate on the "first_entry_at" field.
func FirstEntryAtLT(v time.Time) predicate.ExternalInformation {
	return predicate.ExternalInformation(sql.FieldLT(FieldFirstEntryAt, v))
}

// FirstEntryAtLTE applies the LTE predicate on the "first_entry_at" field.
func FirstEntryAtLTE(v time.Time) predicate.ExternalInformation {
	return predicate.ExternalInformation(sql.FieldLTE(FieldFirstEntryAt, v))
}

// LastUpdatedAtEQ applies the EQ predicate on the "last_updated_at" field.
func LastUpdatedAtEQ(v time.Time) predicate.ExternalInformation {
	return predicate.ExternalInformation(sql.FieldEQ(FieldLastUpdatedAt, v))
}

// LastUpdatedAtNEQ applies the NEQ predicate on the "last_updated_at" field.
func LastUpdatedAtNEQ(v time.Time) predicate.ExternalInformation {
	return predicate.ExternalInformation(sql.FieldNEQ(FieldLastUpdatedAt, v))
}

// LastUpdatedAtIn applies the In predicate on the "last_updated_at" field.
func LastUpdatedAtIn(vs ...time.Time) predicate.ExternalInformation {
	return predicate.ExternalInformation(sql.FieldIn(FieldLastUpdatedAt, vs...))
}

// LastUpdatedAtNotIn applies the NotIn predicate on the "last_updated_at" field.
func LastUpdatedAtNotIn(vs ...time.Time) predicate.ExternalInformation {
	return predicate.ExternalInformation(sql.FieldNotIn(FieldLastUpdatedAt, vs...))
}

// LastUpdatedAtGT applies the GT predicate on the "last_updated_at" field.
func LastUpdatedAtGT(v time.Time) predicate.ExternalInformation {
	return predicate.ExternalInformation(sql.FieldGT(FieldLastUpdatedAt, v))
}

// LastUpdatedAtGTE applies the GTE predicate on the "last_updated_at" field.
func LastUpdatedAtGTE(v time.Time) predicate.ExternalInformation {
	return predicate.ExternalInformation(sql.FieldGTE(FieldLastUpdatedAt, v))
}

// LastUpdatedAtLT applies the LT predicate on the "last_updated_at" field.
func LastUpdatedAtLT(v time.Time) predicate.ExternalInformation {
	return predicate.ExternalInformation(sql.FieldLT(FieldLastUpdatedAt, v))
}

// LastUpdatedAtLTE applies the LTE predicate on the "last_updated_at" field.
func LastUpdatedAtLTE(v time.Time) predicate.ExternalInformation {
	return predicate.ExternalInformation(sql.FieldLTE(FieldLastUpdatedAt, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.ExternalInformation) predicate.ExternalInformation {
	return predicate.ExternalInformation(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.ExternalInformation) predicate.ExternalInformation {
	return predicate.ExternalInformation(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.ExternalInformation) predicate.ExternalInformation {
	return predicate.ExternalInformation(sql.NotPredicates(p))
}
